-- MySQL Script generated by MySQL Workbench
-- Tue Dec 29 20:50:29 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Direccion` (
  `idDireccion` INT NOT NULL COMMENT '',
  `Nombre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idDireccion`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Area` (
  `idArea` INT NOT NULL COMMENT '',
  `Nombre` VARCHAR(45) NULL COMMENT '',
  `Direccion_idDireccion` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idArea`)  COMMENT '',
  INDEX `fk_Area_Direccion_idx` (`Direccion_idDireccion` ASC)  COMMENT '',
  CONSTRAINT `fk_Area_Direccion`
    FOREIGN KEY (`Direccion_idDireccion`)
    REFERENCES `mydb`.`Direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `idDepartamento` INT NOT NULL COMMENT '',
  `Nombre` VARCHAR(45) NULL COMMENT '',
  `Area_idArea` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idDepartamento`)  COMMENT '',
  INDEX `fk_Departamento_Area1_idx` (`Area_idArea` ASC)  COMMENT '',
  CONSTRAINT `fk_Departamento_Area1`
    FOREIGN KEY (`Area_idArea`)
    REFERENCES `mydb`.`Area` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ubicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ubicacion` (
  `idUbicacion` INT NOT NULL COMMENT '',
  `Nombre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idUbicacion`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Escolaridad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Escolaridad` (
  `idEscolaridad` INT NOT NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idEscolaridad`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado` (
  `idEstado` INT NOT NULL COMMENT '',
  `Nombre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idEstado`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Municipio` (
  `idMunicipio` INT NOT NULL COMMENT '',
  `Estado_idEstado` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idMunicipio`)  COMMENT '',
  INDEX `fk_Municipio_Estado1_idx` (`Estado_idEstado` ASC)  COMMENT '',
  CONSTRAINT `fk_Municipio_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `mydb`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Colaborador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Colaborador` (
  `numEmpleado` INT NOT NULL COMMENT '',
  `jefeNumEmpleado` INT NULL COMMENT '',
  `estatus` VARCHAR(45) NULL COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `apellidoPaterno` VARCHAR(45) NULL COMMENT '',
  `apellidoMaterno` VARCHAR(45) NULL COMMENT '',
  `sexo` VARCHAR(45) NULL COMMENT '',
  `Escolaridad_idEscolaridad` INT NOT NULL COMMENT '',
  `curp` VARCHAR(45) NULL COMMENT '',
  `rfc` VARCHAR(45) NULL COMMENT '',
  `NSS` VARCHAR(45) NULL COMMENT '',
  `Direccion` VARCHAR(45) NULL COMMENT '',
  `Colonia` VARCHAR(45) NULL COMMENT '',
  `CP` INT NULL COMMENT '',
  `Municipio_idMunicipio` INT NOT NULL COMMENT '',
  `fechaNac` DATE NULL COMMENT '',
  `TelCasa` VARCHAR(45) NULL COMMENT '',
  `TelCelular` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`numEmpleado`)  COMMENT '',
  INDEX `fk_Colaborador_Colaborador1_idx` (`jefeNumEmpleado` ASC)  COMMENT '',
  INDEX `fk_Colaborador_Escolaridad1_idx` (`Escolaridad_idEscolaridad` ASC)  COMMENT '',
  INDEX `fk_Colaborador_Municipio1_idx` (`Municipio_idMunicipio` ASC)  COMMENT '',
  CONSTRAINT `fk_Colaborador_Colaborador1`
    FOREIGN KEY (`jefeNumEmpleado`)
    REFERENCES `mydb`.`Colaborador` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colaborador_Escolaridad1`
    FOREIGN KEY (`Escolaridad_idEscolaridad`)
    REFERENCES `mydb`.`Escolaridad` (`idEscolaridad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colaborador_Municipio1`
    FOREIGN KEY (`Municipio_idMunicipio`)
    REFERENCES `mydb`.`Municipio` (`idMunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Puesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Puesto` (
  `clave` VARCHAR(15) NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`clave`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turno` (
  `idTurno` INT NOT NULL COMMENT '',
  `Nombre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idTurno`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Regimen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Regimen` (
  `idRegimen` INT NOT NULL COMMENT '',
  `Nombre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idRegimen`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Posicion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Posicion` (
  `idPosicion` INT NOT NULL COMMENT '',
  `Puesto_clave` VARCHAR(15) NULL COMMENT '',
  `Departamento_idDepartamento` INT NOT NULL COMMENT '',
  `Colaborador_numEmpleado` INT NOT NULL COMMENT '',
  `sueldoDiario` DECIMAL(2) NULL COMMENT '',
  `Turno_idTurno` INT NOT NULL COMMENT '',
  `Regimen_idRegimen` INT NOT NULL COMMENT '',
  `Ubicacion_idUbicacion` INT NOT NULL COMMENT '',
  `sueldoMensual` VARCHAR(45) NULL COMMENT '',
  `Colaborador_numEmpleado1` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idPosicion`)  COMMENT '',
  INDEX `fk_Posicion_Puesto1_idx` (`Puesto_clave` ASC)  COMMENT '',
  INDEX `fk_Posicion_Departamento1_idx` (`Departamento_idDepartamento` ASC)  COMMENT '',
  INDEX `fk_Posicion_Turno1_idx` (`Turno_idTurno` ASC)  COMMENT '',
  INDEX `fk_Posicion_Regimen1_idx` (`Regimen_idRegimen` ASC)  COMMENT '',
  INDEX `fk_Posicion_Ubicacion1_idx` (`Ubicacion_idUbicacion` ASC)  COMMENT '',
  INDEX `fk_Posicion_Colaborador1_idx` (`Colaborador_numEmpleado1` ASC)  COMMENT '',
  CONSTRAINT `fk_Posicion_Puesto1`
    FOREIGN KEY (`Puesto_clave`)
    REFERENCES `mydb`.`Puesto` (`clave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Posicion_Departamento1`
    FOREIGN KEY (`Departamento_idDepartamento`)
    REFERENCES `mydb`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Posicion_Turno1`
    FOREIGN KEY (`Turno_idTurno`)
    REFERENCES `mydb`.`Turno` (`idTurno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Posicion_Regimen1`
    FOREIGN KEY (`Regimen_idRegimen`)
    REFERENCES `mydb`.`Regimen` (`idRegimen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Posicion_Ubicacion1`
    FOREIGN KEY (`Ubicacion_idUbicacion`)
    REFERENCES `mydb`.`Ubicacion` (`idUbicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Posicion_Colaborador1`
    FOREIGN KEY (`Colaborador_numEmpleado1`)
    REFERENCES `mydb`.`Colaborador` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Motivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Motivos` (
  `idMotivos` INT NOT NULL COMMENT '',
  `Nombre` VARCHAR(45) NULL COMMENT '',
  `Descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idMotivos`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bajas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bajas` (
  `idBajas` INT NOT NULL COMMENT '',
  `Colaborador_numEmpleado` INT NOT NULL COMMENT '',
  `fechaBaja` DATETIME NULL COMMENT '',
  `Motivos_idMotivos` INT NOT NULL COMMENT '',
  `fechaBaja2` DATETIME NULL COMMENT '',
  PRIMARY KEY (`idBajas`)  COMMENT '',
  INDEX `fk_Bajas_Colaborador1_idx` (`Colaborador_numEmpleado` ASC)  COMMENT '',
  INDEX `fk_Bajas_Motivos1_idx` (`Motivos_idMotivos` ASC)  COMMENT '',
  CONSTRAINT `fk_Bajas_Colaborador1`
    FOREIGN KEY (`Colaborador_numEmpleado`)
    REFERENCES `mydb`.`Colaborador` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bajas_Motivos1`
    FOREIGN KEY (`Motivos_idMotivos`)
    REFERENCES `mydb`.`Motivos` (`idMotivos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Altas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Altas` (
  `idAltas` INT NOT NULL COMMENT '',
  `fechaAlta` VARCHAR(45) NULL COMMENT '',
  `Colaborador_numEmpleado` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idAltas`)  COMMENT '',
  INDEX `fk_Altas_Colaborador1_idx` (`Colaborador_numEmpleado` ASC)  COMMENT '',
  CONSTRAINT `fk_Altas_Colaborador1`
    FOREIGN KEY (`Colaborador_numEmpleado`)
    REFERENCES `mydb`.`Colaborador` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`altasPosicion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`altasPosicion` (
  `idaltasPosicion` INT NOT NULL COMMENT '',
  `fecha` DATETIME NULL COMMENT '',
  `Posicion_idPosicion` INT NOT NULL COMMENT '',
  `Posicion_Colaborador_numEmpleado` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idaltasPosicion`)  COMMENT '',
  INDEX `fk_altasPosicion_Posicion1_idx` (`Posicion_idPosicion` ASC, `Posicion_Colaborador_numEmpleado` ASC)  COMMENT '',
  CONSTRAINT `fk_altasPosicion_Posicion1`
    FOREIGN KEY (`Posicion_idPosicion` , `Posicion_Colaborador_numEmpleado`)
    REFERENCES `mydb`.`Posicion` (`idPosicion` , `Colaborador_numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tranferencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tranferencias` (
  `idTranferencias` INT NOT NULL COMMENT '',
  `fecha` VARCHAR(45) NULL COMMENT '',
  `puestoAnterior` VARCHAR(45) NULL COMMENT '',
  `sueldoAnterior` VARCHAR(45) NULL COMMENT '',
  `puestoNuevo` VARCHAR(45) NULL COMMENT '',
  `sueldoNuevo` VARCHAR(45) NULL COMMENT '',
  `Colaborador_numEmpleado` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idTranferencias`)  COMMENT '',
  INDEX `fk_Tranferencias_Colaborador1_idx` (`Colaborador_numEmpleado` ASC)  COMMENT '',
  CONSTRAINT `fk_Tranferencias_Colaborador1`
    FOREIGN KEY (`Colaborador_numEmpleado`)
    REFERENCES `mydb`.`Colaborador` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
