-- MySQL Script generated by MySQL Workbench
-- Sun Dec 27 21:43:26 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Direccion` (
  `idDireccion` INT NOT NULL COMMENT '',
  `Nombre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idDireccion`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Area` (
  `idArea` INT NOT NULL COMMENT '',
  `Nombre` VARCHAR(45) NULL COMMENT '',
  `Direccion_idDireccion` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idArea`)  COMMENT '',
  INDEX `fk_Area_Direccion_idx` (`Direccion_idDireccion` ASC)  COMMENT '',
  CONSTRAINT `fk_Area_Direccion`
    FOREIGN KEY (`Direccion_idDireccion`)
    REFERENCES `mydb`.`Direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `idDepartamento` INT NOT NULL COMMENT '',
  `Nombre` VARCHAR(45) NULL COMMENT '',
  `Area_idArea` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idDepartamento`)  COMMENT '',
  INDEX `fk_Departamento_Area1_idx` (`Area_idArea` ASC)  COMMENT '',
  CONSTRAINT `fk_Departamento_Area1`
    FOREIGN KEY (`Area_idArea`)
    REFERENCES `mydb`.`Area` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ubicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ubicacion` (
  `idUbicacion` INT NOT NULL COMMENT '',
  `Nombre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idUbicacion`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Puesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Puesto` (
  `clave` VARCHAR(15) NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`clave`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Posicion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Posicion` (
  `idPosicion` INT NOT NULL COMMENT '',
  `Puesto_clave` VARCHAR(15) NULL COMMENT '',
  `Departamento_idDepartamento` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idPosicion`)  COMMENT '',
  INDEX `fk_Posicion_Puesto1_idx` (`Puesto_clave` ASC)  COMMENT '',
  INDEX `fk_Posicion_Departamento1_idx` (`Departamento_idDepartamento` ASC)  COMMENT '',
  CONSTRAINT `fk_Posicion_Puesto1`
    FOREIGN KEY (`Puesto_clave`)
    REFERENCES `mydb`.`Puesto` (`clave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Posicion_Departamento1`
    FOREIGN KEY (`Departamento_idDepartamento`)
    REFERENCES `mydb`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turno` (
  `idTurno` INT NOT NULL COMMENT '',
  `Nombre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idTurno`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Regimen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Regimen` (
  `idRegimen` INT NOT NULL COMMENT '',
  `Nombre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idRegimen`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Colaborador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Colaborador` (
  `numEmpleado` INT NOT NULL COMMENT '',
  `Ubicacion_idUbicacion` INT NOT NULL COMMENT '',
  `sueldo` DECIMAL(2) NULL COMMENT '',
  `jefeNumEmpleado` INT NULL COMMENT '',
  `Posicion_idPosicion` INT NULL COMMENT '',
  `Turno_idTurno` INT NOT NULL COMMENT '',
  `Regimen_idRegimen` INT NOT NULL COMMENT '',
  `fechaIngreso` DATE NULL COMMENT '',
  `fechaBaja` DATE NULL COMMENT '',
  PRIMARY KEY (`numEmpleado`)  COMMENT '',
  INDEX `fk_Colaborador_Ubicacion1_idx` (`Ubicacion_idUbicacion` ASC)  COMMENT '',
  INDEX `fk_Colaborador_Colaborador1_idx` (`jefeNumEmpleado` ASC)  COMMENT '',
  INDEX `fk_Colaborador_Posicion1_idx` (`Posicion_idPosicion` ASC)  COMMENT '',
  INDEX `fk_Colaborador_Turno1_idx` (`Turno_idTurno` ASC)  COMMENT '',
  INDEX `fk_Colaborador_Regimen1_idx` (`Regimen_idRegimen` ASC)  COMMENT '',
  CONSTRAINT `fk_Colaborador_Ubicacion1`
    FOREIGN KEY (`Ubicacion_idUbicacion`)
    REFERENCES `mydb`.`Ubicacion` (`idUbicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colaborador_Colaborador1`
    FOREIGN KEY (`jefeNumEmpleado`)
    REFERENCES `mydb`.`Colaborador` (`numEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colaborador_Posicion1`
    FOREIGN KEY (`Posicion_idPosicion`)
    REFERENCES `mydb`.`Posicion` (`idPosicion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colaborador_Turno1`
    FOREIGN KEY (`Turno_idTurno`)
    REFERENCES `mydb`.`Turno` (`idTurno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colaborador_Regimen1`
    FOREIGN KEY (`Regimen_idRegimen`)
    REFERENCES `mydb`.`Regimen` (`idRegimen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
